# Generated by Django 5.1.1 on 2024-09-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankloan',
            fields=[
                ('Loanid', models.IntegerField(primary_key=True, serialize=False)),
                ('CreditRate', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Account_No', models.IntegerField()),
                ('Reason', models.CharField(max_length=500)),
            ],
        ),
    ]
